name: automatic deployment

on:
  push:
    branches:
      - master

jobs:
  initialize:
    name: initialize environment
    runs-on: ubuntu-latest
    steps:
      - name: decrypt
        env:
          ssh_config: ${{ secrets.ssh_config }}
          root_rsa: ${{ secrets.root_rsa }}
          en_rsa: ${{ secrets.en_rsa }}
          zh_rsa: ${{ secrets.zh_rsa }}
        run: |
          mkdir ~/.ssh
          echo "$ssh_config" > ~/.ssh/config
          echo "$root_rsa" > ~/.ssh/root_rsa
          echo "$en_rsa" > ~/.ssh/en_rsa
          echo "$zh_rsa" > ~/.ssh/zh_rsa

      - name: clone
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: setup
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: install
        run: |
          npm install -g npm@latest
          npm install -g hexo-cli

      - name: config
        run: |
          export TZ=Asia/Shanghai
          git config --global core.quotepath off
          git config --global user.name "Jialin He"
          git config --global user.email "xprtion@outlook.com"

  root:
    name: deploy root
    runs-on: ubuntu-latest
    needs: initialize
    steps:
      - name: status
        run: |
          pwd
          ls
          git status

      - name: pull
        run: |
          cd Blogs
          git remote add root git@bitrhythm.github.io:Bitrhythm/bitrhythm.github.io.git
          git subtree add --prefix=root/public/ root master --squash

      - name: generate
        run: |
          cd root
          rm -rf public/ && cp -r source/ public/
          cd ..

      - name: push
        run: |
          git add -f root/public/
          git commit --allow-empty -m "Deployed by GitHub Actions"
          git subtree split --prefix=root/public/ --branch root
          git subtree push --prefix=root/public/ root master --squash

  en:
    name: deploy en
    runs-on: ubuntu-latest
    needs: initialize
    steps:
      - name: status
        run: |
          pwd
          ls
          git status

      - name: pull
        run: |
          cd Blogs
          git remote add en git@en.bitrhythm.github.io:Bitrhythm/en.git
          git subtree add --prefix=en/public/ en master --squash

      - name: generate
        run: |
          cd en
          npm install && npm update && npm audit fix
          hexo clean && hexo generate
          cd ..

      - name: push
        run: |
          git add en/package.json en/package-lock.json
          git add -f en/public/
          git commit --allow-empty -m "Deployed by GitHub Actions"
          git subtree split --prefix=en/public/ --branch en
          git subtree push --prefix=en/public/ en master --squash

  zh:
    name: deploy zh
    runs-on: ubuntu-latest
    needs: initialize
    steps:
      - name: status
        run: |
          pwd
          ls
          git status

      - name: pull
        run: |
          cd Blogs
          git remote add zh git@zh.bitrhythm.github.io:Bitrhythm/zh.git
          git subtree add --prefix=zh/public/ zh master --squash

      - name: generate
        run: |
          cd zh
          npm install && npm update && npm audit fix
          hexo clean && hexo generate
          cd ..

      - name: push
        run: |
          git add zh/package.json zh/package-lock.json
          git add -f zh/public/
          git commit --allow-empty -m "Deployed by GitHub Actions"
          git subtree split --prefix=zh/public/ --branch zh
          git subtree push --prefix=zh/public/ zh master --squash
